# Generated by Django 5.0.1 on 2024-01-17 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_userprofile_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="avatar",
        ),
    ]
