# Generated by Django 5.0.1 on 2024-01-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0003_remove_userprofile_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="liked_games",
            field=models.ManyToManyField(to="main_app.game"),
        ),
    ]
