# Generated by Django 5.0.1 on 2024-01-19 14:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0006_alter_game_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="genres",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
