# Generated by Django 5.0.1 on 2024-01-19 15:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0007_alter_game_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="genres",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="platforms",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=250),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
